default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: mixed-line-ending
        args: [--fix=lf]
        stages: [commit]

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c "npm run lint"
        language: system
        types_or: [javascript, ts, jsx, tsx]
